(function(){
  "use strict";
  const DF=window.DF;
  const ICONS={
    home:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m3 11 9-8 9 8"/><path d="M5 10v11h14V10M9 21v-7h6v7"/></svg>',
    words:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 5h16M4 12h16M4 19h16"/><path d="M8 3v4M8 10v4M8 17v4"/></svg>',
    study:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2Z"/></svg>',
    stats:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>',
    settings:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21h-4v-.09A1.7 1.7 0 0 0 8.6 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H3v-4h.09A1.7 1.7 0 0 0 4.6 8.6a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V3h4v.09A1.7 1.7 0 0 0 15.4 4.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.16.37.38.7.65.98.3.3.7.44 1.12.42H21v4h-.09A1.7 1.7 0 0 0 19.4 15Z"/></svg>',
    sun:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/></svg>',
    plus:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 5v14M5 12h14"/></svg>'
  };

  function toast(message,type=""){const root=document.getElementById("toast-root"),el=document.createElement("div");el.className=`toast ${type}`;el.textContent=message;root.appendChild(el);setTimeout(()=>el.remove(),2600);}
  function modal(html){document.getElementById("modal-root").innerHTML=`<div class="modal-backdrop" data-action="modal-backdrop"><section class="modal" role="dialog" aria-modal="true">${html}</section></div>`;}
  function closeModal(){document.getElementById("modal-root").innerHTML="";}
  function statusLabel(s){return({new:"جديدة",learning:"قيد التعلم",due:"مستحقة",overdue:"متأخرة",weak:"ضعيفة",mastered:"متقنة",ignored:"مستبعدة"})[s]||s;}
  function statusPill(s){const cls=s==="overdue"?"weak":s;return `<span class="pill ${cls}">${statusLabel(s)}</span>`;}
  function routeLabel(route){return({home:"الرئيسية",words:"الكلمات",study:"تعلّم",stats:"الإحصائيات",settings:"الإعدادات"})[route]||route;}
  function modeLabel(mode){return({daily:"جلسة اليوم",new:"كلمات جديدة",due:"المراجعات المستحقة",weak:"الكلمات الضعيفة",mistakes:"مراجعة الأخطاء",article:"اختبار الأدوات",writing:"اختبار الكتابة",quick:"اختبار سريع"})[mode]||"جلسة تعلم";}

  function applyTheme(settings){const dark=settings.theme==="dark"||(settings.theme==="auto"&&matchMedia("(prefers-color-scheme:dark)").matches);document.documentElement.dataset.theme=dark?"dark":"light";document.querySelector('meta[name="theme-color"]')?.setAttribute("content",dark?"#08101f":"#0f766e");}

  function render(state){
    applyTheme(state.settings);
    const app=document.getElementById("app");
    if(state.route==="study"){app.innerHTML=renderStudy(state);afterRender(state);return;}
    app.innerHTML=`<div class="layout">${renderTopbar(state)}<main class="content">${renderPage(state)}</main></div>${renderNav(state)}`;
    afterRender(state);
  }
  function renderTopbar(state){return `<header class="topbar"><div class="brand"><span class="logo">DF</span><div>DeutschFlow<small>تعلّم الألمانية بذكاء</small></div></div><div class="top-actions"><button class="icon-btn" data-action="cycle-theme" title="تغيير المظهر">${ICONS.sun}</button>${state.installPrompt?'<button class="ghost-btn hide-mobile" data-action="install-app">تثبيت التطبيق</button>':''}</div></header>`;}
  function renderNav(state){const routes=[["home",ICONS.home,"الرئيسية"],["words",ICONS.words,"الكلمات"],["study",ICONS.study,"تعلّم"],["stats",ICONS.stats,"الإحصائيات"],["settings",ICONS.settings,"الإعدادات"]];return `<nav class="bottom-nav">${routes.map(([r,i,l])=>`<button class="nav-btn ${state.route===r?'active':''}" data-action="nav" data-route="${r}">${i}<span>${l}</span></button>`).join("")}</nav>`;}
  function renderPage(state){if(state.route==="words")return renderWords(state);if(state.route==="stats")return renderStats(state);if(state.route==="settings")return renderSettings(state);return renderHome(state);}

  function dashboardStats(state){
    const counts={new:0,learning:0,due:0,overdue:0,weak:0,mastered:0,ignored:0};
    for(const w of state.words){counts[DF.wordStatus(w,state.cards)]++;}
    return counts;
  }
  function renderHome(state){
    const c=dashboardStats(state),dueCards=state.cards.filter(x=>!x.suspended&&x.dueAt<=Date.now()).length,quality=state.words.filter(w=>w.qualityStatus==="review").length;
    const resume=state.session&&!state.session.done?`<div class="card" style="margin-bottom:14px;border-inline-start:4px solid var(--warning)"><div class="hero-row"><div><strong>جلسة غير مكتملة</strong><p style="margin:4px 0 0;color:var(--muted);font-size:13px">${modeLabel(state.session.mode)} · ${state.session.initialCompleted} من ${state.session.initialCards} عناصر أساسية</p></div><button class="primary-btn" data-action="resume-session">متابعة</button></div></div>`:"";
    return `<section class="page-head"><div><h1>مرحباً، لنبدأ المراجعة</h1><p>الأسئلة والتكرار يتكيفان مع مستوى كل مهارة بصورة مستقلة.</p></div></section>
      ${resume}
      <section class="card hero"><div class="hero-row"><div><h2>جلسة اليوم</h2><p>المستحق أولاً، ثم الكلمات الجديدة. النطق لا يظهر في سؤال الاستدعاء إلا عند طلب التلميح.</p><div class="hero-metrics"><div class="hero-metric"><strong>${dueCards.toLocaleString("ar-EG")}</strong><span>بطاقة مستحقة</span></div><div class="hero-metric"><strong>${state.settings.newPerDay}</strong><span>كلمة جديدة مستهدفة</span></div><div class="hero-metric"><strong>${state.profile.streak||0}</strong><span>يوم متتالٍ</span></div></div></div><button class="primary-btn large" data-action="start-session" data-mode="daily">ابدأ الجلسة</button></div></section>
      <div class="section-title">نظرة عامة</div><section class="grid grid-4">
        ${statCard("✦",c.new,"جديدة","metric-blue")}${statCard("↻",c.due+c.overdue,"مستحقة","metric-amber")}${statCard("!",c.weak,"ضعيفة","metric-red")}${statCard("✓",c.mastered,"متقنة","metric-green")}
      </section>
      <div class="section-title">تدريبات مخصصة</div><section class="grid grid-3 training-grid">
        ${trainingCard("✍","اختبار الكتابة","استدعاء العربية وكتابة الألمانية دون كشف الإجابة","writing")}
        ${trainingCard("D","اختبار الأدوات","تدريب مستقل على der / die / das","article")}
        ${trainingCard("⏱","اختبار سريع","عشر بطاقات من أهم ما يحتاج إلى مراجعة","quick")}
        ${trainingCard("↻","المراجعات المستحقة","البطاقات التي حان موعدها فقط","due")}
        ${trainingCard("!","الكلمات الضعيفة","الأكثر تعثراً وفق سجل المحاولات","weak")}
        ${trainingCard("×","مراجعة الأخطاء","البطاقات ذات الأخطاء السابقة","mistakes")}
      </section>
      ${quality?`<div class="section-title">جودة البيانات</div><section class="card"><div class="hero-row"><div><strong>${quality.toLocaleString("ar-EG")} مدخلاً يحتاج إلى مراجعة</strong><p style="color:var(--muted);margin:5px 0 0;font-size:13px">تم اكتشافها بقواعد تحقق هيكلية؛ لا يعني ذلك أن جميعها خاطئة لغوياً.</p></div><button class="ghost-btn" data-action="quality-review">فتح المراجعة</button></div></section>`:""}`;
  }
  function statCard(icon,n,label,cls=""){return `<div class="card stat-card ${cls}"><span class="stat-icon">${icon}</span><div><strong>${Number(n||0).toLocaleString("ar-EG")}</strong><span>${label}</span></div></div>`;}
  function trainingCard(icon,title,desc,mode){return `<button class="card interactive training-card" data-action="start-session" data-mode="${mode}"><span class="training-icon">${icon}</span><span><h3>${title}</h3><p>${desc}</p></span></button>`;}

  function getFilteredWords(state){
    const v=state.wordView,q=DF.normalizeGerman(v.query||""),qa=DF.normalizeArabic(v.query||"");let list=state.words.slice();
    if(q||qa)list=list.filter(w=>w.normalizedGerman.includes(q)||w.normalizedArabic.includes(qa)||(w.pronunciation||"").includes(v.query));
    list=list.filter(w=>{const s=DF.wordStatus(w,state.cards);if(v.filter==="all")return true;if(v.filter==="favorite")return w.favorite;if(v.filter==="quality")return w.qualityStatus==="review";if(v.filter==="noun")return w.itemType==="noun";if(v.filter==="due")return s==="due"||s==="overdue";return s===v.filter;});
    if(v.sort==="alpha")list.sort((a,b)=>a.normalizedGerman.localeCompare(b.normalizedGerman,"de"));
    if(v.sort==="mastery")list.sort((a,b)=>DF.wordMastery(a,state.cards)-DF.wordMastery(b,state.cards));
    if(v.sort==="errors")list.sort((a,b)=>wordErrors(state,b.id)-wordErrors(state,a.id));
    if(v.sort==="recent")list.sort((a,b)=>b.updatedAt-a.updatedAt);
    return list;
  }
  function wordErrors(state,id){return state.cards.filter(c=>c.wordId===id).reduce((s,c)=>s+(c.wrong||0),0);}
  function renderWords(state){
    const list=getFilteredWords(state),shown=list.slice(0,state.wordView.limit);
    const filters=[["all","الكل"],["new","جديدة"],["due","مستحقة"],["weak","ضعيفة"],["mastered","متقنة"],["favorite","المفضلة"],["noun","الأسماء"],["quality","تحتاج مراجعة"],["ignored","مستبعدة"]];
    return `<section class="page-head"><div><h1>الكلمات</h1><p>إدارة ${state.words.length.toLocaleString("ar-EG")} كلمة وعبارة مع متابعة الإتقان لكل مهارة.</p></div><button class="primary-btn" data-action="add-word">${ICONS.plus} إضافة كلمة</button></section>
      <div class="toolbar"><input id="word-search" class="search-input" placeholder="بحث بالألمانية أو العربية أو النطق…" value="${DF.esc(state.wordView.query)}"><button class="ghost-btn" data-action="import-open">استيراد</button><select id="word-sort" class="field-select sort-select"><option value="alpha" ${state.wordView.sort==='alpha'?'selected':''}>أبجدي</option><option value="mastery" ${state.wordView.sort==='mastery'?'selected':''}>الأقل إتقاناً</option><option value="errors" ${state.wordView.sort==='errors'?'selected':''}>الأكثر خطأً</option><option value="recent" ${state.wordView.sort==='recent'?'selected':''}>الأحدث تعديلاً</option></select></div>
      <div class="chips">${filters.map(([f,l])=>`<button class="chip ${state.wordView.filter===f?'active':''}" data-action="word-filter" data-filter="${f}">${l}</button>`).join("")}</div>
      <div style="color:var(--muted);font-size:13px;margin-bottom:9px">${list.length.toLocaleString("ar-EG")} نتيجة</div>
      <section class="card list-card">${shown.length?shown.map(w=>wordRow(state,w)).join(""):'<div class="empty">لا توجد كلمات مطابقة.</div>'}</section>
      ${shown.length<list.length?`<button class="ghost-btn load-more" data-action="load-more">عرض المزيد</button>`:""}`;
  }
  function wordRow(state,w){const status=DF.wordStatus(w,state.cards),mastery=DF.wordMastery(w,state.cards);return `<article class="word-row" data-action="edit-word" data-id="${w.id}"><div class="word-main"><div class="word-german" lang="de">${DF.esc(w.german)}</div><div class="word-arabic">${DF.esc(w.arabic)}${w.pronunciation?` · ${DF.esc(w.pronunciation)}`:""}</div></div><div class="word-side">${w.favorite?'⭐':''}${w.qualityStatus==='review'?'<span class="pill due">بيانات</span>':''}<span class="pill">${mastery}%</span>${statusPill(status)}</div></article>`;}

  function renderStats(state){
    const counts=dashboardStats(state),attempts=state.recentAttempts||[],days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=DF.localDateKey(d),n=attempts.filter(a=>DF.localDateKey(new Date(a.createdAt))===key).length;days.push({label:new Intl.DateTimeFormat("ar-EG",{weekday:"short"}).format(d),n});}
    const max=Math.max(1,...days.map(x=>x.n));
    const skills=["recall","recognition","article","order"].map(skill=>{const cards=state.cards.filter(c=>c.skill===skill);return {skill,value:cards.length?Math.round(cards.reduce((s,c)=>s+DF.cardMastery(c),0)/cards.length):0,count:cards.length};});
    const top=state.cards.filter(c=>c.wrong>0).sort((a,b)=>b.wrong-a.wrong).slice(0,8);
    return `<section class="page-head"><div><h1>الإحصائيات</h1><p>النتائج مبنية على محاولات حقيقية وليست على عدد مرات عرض الكلمات.</p></div></section>
      <section class="grid grid-4">${statCard("✓",counts.mastered,"كلمة متقنة","metric-green")}${statCard("↻",counts.due+counts.overdue,"كلمة مستحقة","metric-amber")}${statCard("!",counts.weak,"كلمة ضعيفة","metric-red")}${statCard("★",state.profile.totalXP||0,"نقطة خبرة","metric-blue")}</section>
      <div class="grid grid-2" style="margin-top:16px"><section class="card"><h3 style="margin-top:0">الإتقان حسب المهارة</h3>${skills.map(x=>skillBar(x)).join("")}</section><section class="card"><h3 style="margin-top:0">نشاط آخر 7 أيام</h3><div class="activity-bars">${days.map(x=>`<div class="day-bar"><b>${x.n}</b><div class="bar" style="height:${Math.max(3,x.n/max*100)}%"></div><small>${x.label}</small></div>`).join("")}</div></section></div>
      <div class="section-title">أكثر البطاقات خطأً</div><section class="card list-card">${top.length?top.map(c=>{const w=state.wordsMap.get(c.wordId);return `<div class="word-row" data-action="edit-word" data-id="${w.id}"><div class="word-main"><div class="word-german" lang="de">${DF.esc(w.german)}</div><div class="word-arabic">${DF.skillLabel(c.skill)}</div></div><div class="word-side"><span class="pill weak">${c.wrong} خطأ</span><span class="pill">${DF.cardMastery(c)}%</span></div></div>`;}).join(""):'<div class="empty">لا توجد أخطاء مسجلة بعد.</div>'}</section>`;
  }
  function skillBar(x){return `<div class="skill-row"><div class="skill-head"><span>${DF.skillLabel(x.skill)} · ${x.count.toLocaleString("ar-EG")} بطاقة</span><strong>${x.value}%</strong></div><div class="mini-progress"><span style="width:${x.value}%"></span></div></div>`;}

  function renderSettings(state){const s=state.settings;return `<section class="page-head"><div><h1>الإعدادات</h1><p>إعدادات الجلسات والتصحيح والبيانات.</p></div></section>
    <div class="grid grid-2"><section class="card settings-group"><h3 style="margin-top:0">الجلسة اليومية</h3>${numberSetting("الكلمات الجديدة يومياً","newPerDay",s.newPerDay,"عدد الكلمات التي تُقدّم لأول مرة.")}${numberSetting("المراجعات يومياً","reviewsPerDay",s.reviewsPerDay,"الحد الأعلى للبطاقات المستحقة.")}${numberSetting("حجم الجلسة","sessionSize",s.sessionSize,"عدد العناصر الأساسية، دون احتساب الإعادات.")}${numberSetting("حد إعادة الخطأ","retryLimit",s.retryLimit,"عدد مرات إعادة البطاقة الخاطئة داخل الجلسة.")}</section>
    <section class="card settings-group"><h3 style="margin-top:0">التصحيح والتلميحات</h3>${toggleSetting("إظهار النطق","showPronunciation",s.showPronunciation,"يظهر في العرض التعليمي أو عند طلب التلميح، وليس تلقائياً في سؤال الاستدعاء.")}${toggleSetting("قبول ae / oe / ue","acceptAeOeUe",s.acceptAeOeUe,"قبول بدائل Umlaut عند الكتابة.")}${toggleSetting("قبول ss بدلاً من ß","acceptSs",s.acceptSs,"لا يلغي عرض الكتابة القياسية في التصحيح.")}${toggleSetting("إلزام أداة الاسم","requireArticle",s.requireArticle,"يُعد الاسم دون der/die/das إجابة ناقصة.")}${toggleSetting("تجاهل ترقيم الجمل","ignoreSentencePunctuation",s.ignoreSentencePunctuation,"النقطة أو الفاصلة لا تجعل الجملة الصحيحة خاطئة.")}</section></div>
    <div class="section-title">المظهر والبيانات</div><section class="grid grid-2"><div class="card"><div class="field"><label>المظهر</label><select id="theme-select" class="field-select"><option value="auto" ${s.theme==='auto'?'selected':''}>تلقائي حسب النظام</option><option value="light" ${s.theme==='light'?'selected':''}>فاتح</option><option value="dark" ${s.theme==='dark'?'selected':''}>داكن</option></select></div>${state.installPrompt?'<button class="ghost-btn block" data-action="install-app">تثبيت كتطبيق</button>':''}</div>
    <div class="card"><div class="grid grid-2"><button class="ghost-btn" data-action="export-backup">نسخة JSON كاملة</button><button class="ghost-btn" data-action="export-csv">تصدير CSV</button><button class="ghost-btn" data-action="restore-open">استعادة نسخة</button><button class="ghost-btn" data-action="import-open">استيراد XLSX/CSV</button></div><button class="danger-btn block" style="margin-top:10px" data-action="reset-app">إعادة ضبط التطبيق</button></div></section>
    <div class="section-title">معلومات</div><section class="card"><p style="margin:0;color:var(--muted);line-height:1.8">DeutschFlow v2 · يعمل دون إنترنت · ${state.words.length.toLocaleString("ar-EG")} مدخلاً · التخزين محلي في IndexedDB. النسخة الاحتياطية ضرورية قبل تغيير المتصفح أو الجهاز.</p></section>`;}
  function numberSetting(title,key,value,desc){return `<div class="setting-row"><div><strong>${title}</strong><p>${desc}</p></div><input class="field-input setting-number" data-setting="${key}" type="number" min="0" max="500" value="${value}" style="width:88px"></div>`;}
  function toggleSetting(title,key,on,desc){return `<div class="setting-row"><div><strong>${title}</strong><p>${desc}</p></div><button class="toggle ${on?'on':''}" data-action="toggle-setting" data-setting="${key}" aria-pressed="${on}"></button></div>`;}

  function renderStudy(state){
    const s=state.session;if(!s)return `<div class="study-layout"><div class="session-end"><h1>لا توجد جلسة نشطة</h1><button class="primary-btn" data-action="nav" data-route="home">العودة</button></div></div>`;
    if(s.done)return renderSessionEnd(state,s);
    const p=DF.Learning.progress(s),q=s.current;
    if(!q)return `<div class="study-layout"><div class="boot-screen"><p>جارٍ إعداد السؤال…</p></div></div>`;
    return `<main class="study-layout"><header class="study-head"><button class="pill" data-action="exit-study">إنهاء</button><div class="study-title">${modeLabel(s.mode)}</div><div class="study-meta">أساسي ${p.completed}/${p.planned}<br>${q.kind==='intro'?`عرض ${s.introduced+1}`:`محاولة ${s.attempts+1}`}</div></header><div class="progress-wrap"><div class="progress"><span style="width:${p.percent}%"></span></div>${p.pendingRetries?`<span class="retry-badge">إعادات ${p.pendingRetries}</span>`:""}</div><div class="score-strip"><span class="ok">صحيح ${s.correctAttempts}</span><span class="no">خطأ ${s.wrongAttempts}</span><span class="hint">تلميحات ${s.hints}</span></div>${q.kind==="intro"?renderIntro(state,q):renderQuestion(state,q)}</main>`;
  }
  function renderIntro(state,q){const w=q.word;return `<section class="card question-card intro-card"><span class="pill new">كلمة جديدة · عرض تعليمي</span><div class="question-de" lang="de">${DF.esc(w.german)}</div>${state.settings.showPronunciation&&w.pronunciation?`<div class="pronunciation">${DF.esc(w.pronunciation)}</div>`:""}<div class="intro-meaning">${DF.esc(w.arabic)}</div><div class="word-details">${w.article?`<span class="pill">الأداة: <b lang="de">${w.article}</b></span>`:""}${w.itemType?`<span class="pill">${itemTypeLabel(w.itemType)}</span>`:""}${w.level?`<span class="pill">${DF.esc(w.level)}</span>`:""}</div></section><div class="intro-actions"><button class="ghost-btn large" data-action="intro-known">أعرفها مسبقاً</button><button class="primary-btn large" data-action="intro-learned">فهمتها — اختبرني لاحقاً</button></div>`;}
  function itemTypeLabel(t){return({noun:"اسم",word:"كلمة",phrase:"تركيب",sentence:"جملة"})[t]||t;}
  function renderQuestion(state,q){
    const result=state.session.result;let prompt=`<section class="card question-card"><div class="question-label">${q.label}</div><div class="${q.promptLang==='de'?'question-de':'question-ar'}" ${q.promptLang==='de'?'lang="de"':''}>${DF.esc(q.prompt)}</div>`;
    const canShowPron=state.settings.showPronunciation&&q.word.pronunciation&&(q.promptLang==="de"||q.usedHint);
    if(canShowPron)prompt+=`<div class="pronunciation">${DF.esc(q.word.pronunciation)}</div>`;
    if(q.usedHint&&q.skill==="recall")prompt+=`<div class="word-details"><span class="pill due">يبدأ بـ <b lang="de">${DF.esc(DF.splitArticle(q.word.german).rest.charAt(0).toUpperCase())}</b></span></div>`;
    prompt+=`</section>`;
    let body="";
    if(q.choices)body=`<div class="choices">${q.choices.map(c=>{let cls="answer-btn";if(result){if(String(c.id)===String(q.correctId))cls+=" correct";else if(String(c.id)===String(state.lastChoice))cls+=" wrong";else cls+=" dim";}return `<button class="${cls}" data-action="choose-answer" data-choice="${DF.esc(c.id)}" ${result?'disabled':''}>${q.skill==='article'?`<span lang="de">${DF.esc(c.label)}</span>`:DF.esc(c.label)}</button>`;}).join("")}</div>`;
    else if(q.skill==="order")body=renderOrder(state,q,result);
    else body=`<input id="answer-input" class="answer-input" lang="de" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="اكتب الإجابة بالألمانية…" ${result?'disabled':''}><div class="answer-actions"><button class="ghost-btn" data-action="hint" ${result||q.usedHint?'disabled':''}>تلميح</button><button class="primary-btn" data-action="submit-writing" ${result?'disabled':''}>تحقق</button></div>${result?'':'<button class="reveal-btn" data-action="reveal-answer">لا أعرفها — أظهر الإجابة</button>'}`;
    return prompt+body+(result?renderFeedback(state,q,result):"");
  }
  function renderOrder(state,q,result){
    const o=state.orderState&&state.orderState.questionId===q.entry.id?state.orderState:{questionId:q.entry.id,selected:[],pool:q.tokens.slice()};state.orderState=o;
    return `<div class="token-area">${o.selected.length?o.selected.map((t,i)=>`<button class="token" data-action="order-undo-at" data-index="${i}" ${result?'disabled':''}>${DF.esc(t)}</button>`).join(""):'<span style="color:var(--muted)">اختر الكلمات بالترتيب</span>'}</div><div class="token-bank">${o.pool.map((t,i)=>`<button class="token" data-action="order-pick" data-index="${i}" ${result?'disabled':''}>${DF.esc(t)}</button>`).join("")}</div><div class="answer-actions"><button class="ghost-btn" data-action="order-reset" ${result||!o.selected.length?'disabled':''}>إعادة</button><button class="primary-btn" data-action="order-submit" ${result||o.pool.length?'disabled':''}>تحقق</button></div>${result?'':'<button class="reveal-btn" data-action="reveal-answer">لا أعرفها — أظهر الإجابة</button>'}`;
  }
  function renderFeedback(state,q,r){const a=r.answer,correct=a.isCorrect;return `<section class="feedback ${correct?'success':'error'}"><h3>${correct?'✓':'✗'} ${DF.esc(a.note)}</h3>${!correct?`<div class="feedback-row"><span>الإجابة الصحيحة</span><strong lang="de">${DF.esc(a.correctAnswer)}</strong></div>`:""}${a.userAnswer?`<div class="feedback-row"><span>إجابتك</span><span lang="de">${DF.esc(a.userAnswer)}</span></div>`:""}<div style="font-size:12px;color:var(--muted);margin-top:12px">${correct?'قيّم صعوبة التذكر لتحديد الموعد التالي:':'ستُسجّل الإجابة كخطأ وتُعاد البطاقة داخل الجلسة.'}</div><div class="rating-row">${correct?ratingButton(2,"صعب",r.suggestedRating)+ratingButton(3,"جيد",r.suggestedRating)+ratingButton(4,"سهل",r.suggestedRating):ratingButton(1,"ثبت الخطأ وأعدها",1)}</div></section>`;}
  function ratingButton(r,label,suggested){return `<button class="rating-btn ${DF.Learning.ratingName(r)}" data-action="rate-answer" data-rating="${r}" style="${r===suggested?'outline:2px solid var(--primary);outline-offset:1px':''}">${label}</button>`;}
  function renderSessionEnd(state,s){const acc=DF.Learning.sessionAccuracy(s);return `<main class="study-layout"><section class="session-end"><div class="end-icon">✓</div><h1>اكتملت الجلسة</h1><p>تم فصل الكلمات الأساسية عن المحاولات والإعادات، لذلك الأرقام أدناه لا تتداخل.</p><div class="end-grid"><div class="end-stat"><strong>${s.initialCards}</strong><span>عناصر أساسية</span></div><div class="end-stat"><strong>${s.attempts}</strong><span>إجمالي المحاولات</span></div><div class="end-stat"><strong>${acc.first==null?'—':acc.first+'%'}</strong><span>دقة أول محاولة</span></div><div class="end-stat"><strong>${acc.attempts==null?'—':acc.attempts+'%'}</strong><span>دقة كل المحاولات</span></div><div class="end-stat"><strong>${s.reveals}</strong><span>عرض إجابة</span></div><div class="end-stat"><strong>${s.hints}</strong><span>تلميحات</span></div><div class="end-stat"><strong>${s.retriesCompleted}</strong><span>إعادات مكتملة</span></div><div class="end-stat"><strong>+${s.xp}</strong><span>نقطة خبرة</span></div></div><div class="grid grid-2"><button class="ghost-btn large" data-action="session-home">العودة للرئيسية</button><button class="primary-btn large" data-action="start-session" data-mode="${s.mode}">جلسة أخرى</button></div></section></main>`;}

  function afterRender(state){
    if(state.route==="study"&&state.session?.current?.kind==="test"&&!state.session.result&&state.session.current.skill==="recall")setTimeout(()=>document.getElementById("answer-input")?.focus(),10);
  }

  function openWordModal(state,word=null){
    const w=word||{id:"",german:"",arabic:"",pronunciation:"",plural:"",level:"",tags:[],acceptedAnswers:[],favorite:false,ignored:false,qualityIssues:[]};
    modal(`<div class="modal-head"><h2>${word?'تعديل الكلمة':'إضافة كلمة'}</h2><button class="modal-close" data-action="modal-close">×</button></div>${w.qualityIssues?.length?`<div class="quality-box">${w.qualityIssues.map(DF.esc).join(" · ")}</div>`:""}<form id="word-form" data-id="${w.id}"><div class="field"><label>الألمانية — مع الأداة إن وجدت</label><input name="german" class="field-input" lang="de" required value="${DF.esc(w.german)}"></div><div class="field"><label>المعنى العربي</label><input name="arabic" class="field-input" required value="${DF.esc(w.arabic)}"></div><div class="form-grid"><div class="field"><label>النطق بالعربية</label><input name="pronunciation" class="field-input" value="${DF.esc(w.pronunciation||'')}"></div><div class="field"><label>صيغة الجمع</label><input name="plural" class="field-input" lang="de" value="${DF.esc(w.plural||'')}"></div><div class="field"><label>المستوى CEFR</label><input name="level" class="field-input" value="${DF.esc(w.level||'')}"></div><div class="field"><label>التصنيفات — مفصولة بفاصلة</label><input name="tags" class="field-input" value="${DF.esc((w.tags||[]).join(', '))}"></div></div><div class="field"><label>إجابات ألمانية بديلة مقبولة — كل إجابة في سطر</label><textarea name="acceptedAnswers" class="field-textarea" lang="de">${DF.esc((w.acceptedAnswers||[]).join('\n'))}</textarea></div><div class="grid grid-2"><label class="setting-row" style="border:1px solid var(--border);border-radius:13px;padding:11px"><span><strong>مفضلة</strong><p>إظهارها ضمن فلتر المفضلة.</p></span><input type="checkbox" name="favorite" ${w.favorite?'checked':''}></label><label class="setting-row" style="border:1px solid var(--border);border-radius:13px;padding:11px"><span><strong>مستبعدة</strong><p>عدم إدراجها في الجلسات.</p></span><input type="checkbox" name="ignored" ${w.ignored?'checked':''}></label></div><div class="modal-actions">${word?'<button type="button" class="danger-btn" data-action="delete-word" data-id="'+w.id+'">حذف</button><button type="button" class="ghost-btn" data-action="reset-word-progress" data-id="'+w.id+'">تصفير التقدم</button>':''}<button type="button" class="ghost-btn" data-action="modal-close">إلغاء</button><button type="submit" class="primary-btn">حفظ</button></div></form>`);
  }
  function openImportModal(){modal(`<div class="modal-head"><h2>استيراد الكلمات</h2><button class="modal-close" data-action="modal-close">×</button></div><p style="color:var(--muted);line-height:1.7">يدعم XLSX وCSV فعلياً. الأعمدة المتوقعة: German/Deutsch، Arabic/المعنى، Pronunciation/النطق، ويمكن إضافة Level وTags وPlural.</p><div class="field"><label>اختر الملف</label><input id="import-file" class="field-input" type="file" accept=".xlsx,.csv,.tsv"></div><div id="import-preview"></div><div class="modal-actions"><button class="ghost-btn" data-action="modal-close">إلغاء</button><button class="primary-btn" data-action="analyze-import">تحليل الملف</button></div>`);}
  function showImportPreview(preview){const root=document.getElementById("import-preview");if(!root)return;root.innerHTML=`<div class="card" style="box-shadow:none;margin-top:12px"><div class="grid grid-4">${statCard("≡",preview.stats.read,"تمت قراءتها")}${statCard("+",preview.stats.added,"جديدة","metric-green")}${statCard("=",preview.stats.duplicates,"مكررة","metric-amber")}${statCard("!",preview.stats.invalid,"غير صالحة","metric-red")}</div>${preview.items.length?`<div class="modal-actions"><button class="primary-btn" data-action="commit-import">إضافة ${preview.items.length.toLocaleString('ar-EG')} كلمة</button></div>`:""}</div>`;}
  function openRestoreModal(){modal(`<div class="modal-head"><h2>استعادة نسخة احتياطية</h2><button class="modal-close" data-action="modal-close">×</button></div><div class="quality-box">ستُستبدل الكلمات والبطاقات والتقدم الحالي بالكامل. صدّر نسخة قبل المتابعة.</div><div class="field"><label>ملف DeutschFlow JSON</label><input id="restore-file" class="field-input" type="file" accept=".json"></div><div class="modal-actions"><button class="ghost-btn" data-action="modal-close">إلغاء</button><button class="danger-btn" data-action="restore-backup">استعادة واستبدال</button></div>`);}
  function openQualityModal(state){const flagged=state.words.filter(w=>w.qualityStatus==="review").slice(0,100);modal(`<div class="modal-head"><h2>مراجعة جودة البيانات</h2><button class="modal-close" data-action="modal-close">×</button></div><p style="color:var(--muted)">هذه إشارات آلية إلى تعارض هيكلي محتمل، وليست حكماً لغوياً نهائياً.</p><div class="quality-list">${flagged.map(w=>`<button class="quality-item card interactive" data-action="quality-edit" data-id="${w.id}" style="text-align:start"><strong lang="de">${DF.esc(w.german)}</strong><small>${DF.esc(w.arabic)} · ${(w.qualityIssues||[]).map(DF.esc).join('، ')}</small></button>`).join("")}</div>${state.words.filter(w=>w.qualityStatus==='review').length>100?'<p style="color:var(--muted)">يُعرض أول 100 مدخل. استخدم فلتر «تحتاج مراجعة» في صفحة الكلمات لعرض الجميع.</p>':''}`);}
  function confirmModal(title,text,action,label="تأكيد",danger=true){modal(`<div class="modal-head"><h2>${DF.esc(title)}</h2><button class="modal-close" data-action="modal-close">×</button></div><p style="color:var(--muted);line-height:1.7">${DF.esc(text)}</p><div class="modal-actions"><button class="ghost-btn" data-action="modal-close">إلغاء</button><button class="${danger?'danger-btn':'primary-btn'}" data-action="${action}">${DF.esc(label)}</button></div>`);}

  Object.assign(DF,{UI:{render,toast,modal,closeModal,openWordModal,openImportModal,showImportPreview,openRestoreModal,openQualityModal,confirmModal,applyTheme,modeLabel,routeLabel}});
})();
